services:
  - type: web
    name: clicsolar-api
    env: python
    region: ohio
    buildCommand: |
      pip install -r requirements.txt
      playwright install chromium
      playwright install-deps chromium
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: TZ
        value: America/Bogota # Change to your timezone
      - key: DB_PATH
        value: /data/sunquote.db
    disk:
      name: sqlite-data
      mountPath: /data
      sizeGB: 1
